###注册 中心
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8100/eureka/
server:
  port: 8080
###网关名称
spring:
  application:
    name: service-zuul
### 配置网关反向代理
zuul:
  routes:
    # 定义转发服务规则，自定义节点api-a
    api-a:
     ### 当客户端发送请求http://zuulIP:80/api-member/开头的 都会转发到会员服务
      path: /api-member/**
      # 会员服务别名（spring.application.name） zuul网关默认整合ribbon,自动实现负载均衡轮询效果。
      serviceId: app-itmayiedu-member
    # 定义转发服务规则，自定义节点api-b
    api-b:
        ### 当客户端发送请求http://zuulIP:80/api-order/开头的 都会转发到订单服务
      path: /api-order/**
      # 订单服务别名（spring.application.name） zuul网关默认整合ribbon,自动实现负载均衡轮询效果。
      serviceId: app-itmayiedu-order
