###注册 中心
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8100/eureka/
server:
  port: 8080
###网关名称
spring:
  application:
    name: service-zuul
  cloud:
    config:
    ####读取环境后缀
      profile: dev
      ####读取config-server注册地址
      discovery:
      #服务配置中心config server端别名
        service-id: config-server
        #开启读取权限
        enabled: true
# 开启所有监控中心接口
management:
  endpoints:
    web:
      exposure:
        include: "*"
