#服务端口号
server:
  port: 8100
#服务名称(Eureka集群需要定义服务名称，并且每个集群Eureka对象服务名称都要同名)
spring:
  application:
    name: app-itmayiedu-eureka-server
#eureka 基本信息配置
eureka:
  instance:
    #注册到eurekaip地址(注册中心IP)
    hostname: 127.0.0.1
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8100/eureka/
    #表示是否需要将自己注册到Eureka Server上(默认为true),本次位单机部署,不需要设置为true;但是注册中心集群时候必须为true;因为集群时,需要提供本Eureka Server可发现性;(即是否注册自己的开关)
    register-with-eureka: false
    #表示是否从Eureka Server获取注册信息(默认为true);这是一个单点的 Eureka Server，不需要同步其他节点的数据，可以设为false
    fetch-registry: false
#  server:
#    # 测试时关闭自我保护机制，保证不可用服务及时踢出
#    enable-self-preservation: false
#    # 剔除失效服务间隔
#    eviction-interval-timer-in-ms: 2000